project:
  type: website

website:
  title: "Khanh N Bui"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: notes/index.qmd
        text: Notes
    right:
      - icon: linkedin
        href: https://linkedin.com/in/YOUR-LINKEDIN
        aria-label: LinkedIn
        target: _blank
      - icon: github
        href: https://github.com/YOUR-GITHUB
        aria-label: GitHub
        target: _blank
      - icon: file-earmark-pdf
        href: resume/resume.pdf
        aria-label: Resume
        target: _blank

format:
  html:
    theme: Zephyr
    css: styles.css
